Update faq.html
ebmdatalab/openprescribing pull request #4462
Opened 2023-11-28 15:59 UTC by speed-vm

Added simple explanation to General section on FAQ about why OP may not match other platforms.

Link to Spot the difference blog [here](https://docs.google.com/document/d/1I-Vs_-xP7140tyBYbkPoLLEucjsqAN7yS4bTHY31YgU/edit#heading=h.6l1ukqjhakhw) if needed.

2023-12-08 15:22 UTC, brianmackenna commented
One small suggestion and its ready to go.

As a team we should discuss the blog before posting

2023-12-08 15:28 UTC, brianmackenna requested changes

2023-12-08 15:28 UTC, brianmackenna commented on openprescribing/templates/faq.html
> +<p>At OpenPrescribing we anticipate that our results will not always be exactly the same as those displayed on alternative data analysis platforms. There are two common reasons for this. Firstly, dif
I think at the very end you should include a line that says something like 

_All our code for data preparation, analysis and visualisation  is openly available on our [Bennett Institute GIthub](https://github.com/ebmdatalab/openprescribing) for inspection and re-use by anyone. Additionally for each measure you have the choice to "View technical details for this measure" to illustrate exactly what we are measuring in code_

2023-12-19 09:26 UTC, richiecroker approved these changes

2023-12-19 09:37 UTC, merged