FAQ update
ebmdatalab/openprescribing pull request #4703
Opened 2024-03-12 17:37 UTC by chrisjwood16

Add section on subscribing/unsubscribing to emails.
Add section on old data.
Fix incorrect link HTML.

2024-04-29 10:08 UTC, richiecroker requested changes

2024-04-29 10:08 UTC, richiecroker commented on openprescribing/templates/faq.html
> +<p>Given our limited resources, we do not routinely provide data not accessible through the website. However, you may be able to access this data yourself. The NHS BSA openly publishes the <a href="h
should we add something like "although the PCA data is not as detailed as the English Prescribing Dataset?

2024-08-05 14:58 UTC, richiecroker commented
@chrisjwood16 just a bump to finish this one

2024-09-30 13:37 UTC, a-d-brown approved these changes

2024-10-28 15:21 UTC, richiecroker approved these changes

2024-10-28 15:22 UTC, merged